### ISSUE TITLE
error during running

### ISSUE THREAD

**Issue by danessel** [iMetOsaka/UNAGI#5]
Hi,
I'm tring to run the nice tool you made but are facing this error:

Traceback (most recent call last):
  File "/media/bulk_01/users/essel002/anaconda3/envs/ONT/lib/python3.9/site-packages/Bio/File.py", line 71, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not GzipFile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/bulk_01/users/essel002/programs/UNAGI/app/unagi.py", line 781, in <module>
    main(sys.argv[1:])
  File "/media/bulk_01/users/essel002/programs/UNAGI/app/unagi.py", line 105, in main
    SeqIO.write(strandedRecords, strandedGzFile, "fastq")
  File "/media/bulk_01/users/essel002/anaconda3/envs/ONT/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 525, in write
    fp.write(format_function(record))
  File "/media/bulk_01/users/essel002/anaconda3/envs/ONT/lib/python3.9/gzip.py", line 284, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'

in stdout:
[2021/03/12 - 18:53:10] Reading the input file
[2021/03/12 - 19:55:46] Finding the different strands in the input reads
[2021/03/12 - 19:55:46] Finding the forwards reads.
[2021/03/12 - 19:57:39] 368121 forwards reads found
[2021/03/12 - 19:57:39] Finding the backwards reads.
[2021/03/12 - 19:59:34] 1113089 backwards reads found
[2021/03/12 - 19:59:34] Getting the reverse complement for the backwards reads.

Any idea how to slve this

**Comment by JungNicolas** [comment]
Hello ! 

Thank you for submitting this error. 
It should be fixed with the latest version of UNAGI (updated just now).
Please let me know if you still have problems after updating.

Regards,
Nicolas.

**Comment by danessel** [comment]
Hi,

Sorry but the pipeline gave another error further on:
Traceback (most recent call last):
  File "/media/bulk_01/users/essel002/programs/UNAGI/app/unagi.py", line 781, in <module>
    main(sys.argv[1:])
  File "/media/bulk_01/users/essel002/programs/UNAGI/app/unagi.py", line 150, in main
    combineCoverage(os.path.join(transitionnalOutputPath,config["positive_coverage_file"]),os.path.join(transitionnalOutputPath,config["negative_coverage_file"]),os.path.join(transitionnalOutputPath,config["total_coverage_file"]))
  File "/media/bulk_01/users/essel002/programs/UNAGI/app/unagi.py", line 688, in combineCoverage
    negline=next(negative)
StopIteration

Danny

**Comment by danessel** [comment]
Hi I installed UNAGI again but the same error pops up unfortunately

Traceback (most recent call last):
  File "/media/bulk_01/users/essel002/programs/UNAGI/app/unagi.py", line 781, in <module>
    main(sys.argv[1:])
  File "/media/bulk_01/users/essel002/programs/UNAGI/app/unagi.py", line 150, in main
    combineCoverage(os.path.join(transitionnalOutputPath,config["positive_coverage_file"]),os.path.join(transitionnalOutputPath,config["negative_coverage_file"]),os.path.join(transitionnalOutputPath,config["total_coverage_file"]))
  File "/media/bulk_01/users/essel002/programs/UNAGI/app/unagi.py", line 688, in combineCoverage
    negline=next(negative)
StopIteration

**Comment by JungNicolas** [comment]
The problem should be fixed in the latest version. 
Thank you for your detailed feedback !
